### ISSUE TITLE
Implementation of queryLoc2refLoc() function

### ISSUE THREAD

**Issue by caspargross** [Bioconductor/GenomicAlignments#13]
Is there a schedule for the implementation of those functions?
```
queryLocs2refLocs()
queryLoc2refLoc()
```
I saw a forum post from 4 years ago with the same question.
Do you take pull requests for this?
Best, Caspar

**Comment by hpages** [comment]
Hi,

Since the addition of `mapFromAlignments()` and `pmapFromAlignments()` to the package, it's not clear that there is still a need for `queryLocs2refLocs()` or `queryLoc2refLoc()`. Do you have a use case that cannot be handled with `mapFromAlignments()` or `pmapFromAlignments()` but that would be handled with `queryLocs2refLocs()` or `queryLoc2refLoc()`?

Thanks,
H.

**Comment by caspargross** [comment]
Hi,

thanks for the reply. You are right, I can solve my problem using the `mapFromAlignments()` function.
Best, Caspar
