### ISSUE TITLE
When I use the readGAlignments .

### ISSUE THREAD

**Issue by wangguiqian** [Bioconductor/GenomicAlignments#31]
![image](https://github.com/Bioconductor/GenomicAlignments/assets/48958211/8a8c4e35-57ad-4527-b3d9-88e7b401e1c8)

When I used the software minimap2 to compare the bam files obtained by comparing ont data, I found a problem when I used this package to read the bam files. My main purpose was to obtain each read of the compared bam files. Start and stop site information in the reference genome.

**Comment by hpages** [comment]
Please always provide a reproducible example and your `sessionInfo()` when reporting an issue with an R package.

The error message you got suggests that the `aln1_file` variable that you supplied to `readGAlignments()` is the empty string. Can you check this variable?

At the root of your problem is your misunderstanding of the purpose and behavior of the `system.file()` function. Please take the time to read about this function by consulting its man page with `?system.file`. You probably don't need it here.

Best,
H.

**Comment by hpages** [comment]
no news good news, I guess
